import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { injectQuery } from '@tanstack/angular-query-experimental';
import { AnalyticLogger } from '../../core/analytic.logger';
import { Animal, Animals } from '../../core/animals';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-projects-page',
  template: `
    <section class="page">
      <h1>Projects</h1>
      <p>Manage projects here.</p>
      <button type="button" class="btn" (click)="trackProjectsViewed()">
        Track "projects viewed" event
      </button>
      <form [formGroup]="form" (ngSubmit)="onSubmit()">
        <label for="name">Animal Name:</label>
        <input id="name" formControlName="name" class="input" /><br />
        <label for="type">Animal Type:</label>
        <input id="type" formControlName="type" class="input" /><br />
        <label for="weight">Animal Weight (kg):</label>
        <input id="weight" formControlName="weight" type="number" class="input" /><br />
        <button type="submit" class="btn" [disabled]="form.invalid">Create Animal</button>
      </form>
      @if (animals.isSuccess()) {
        <section class="mt-3">
          <h2 class="text-lg">Animals</h2>
          <ul class="mt-2">
            @for(animal of animals.data(); track animal.id) {
              <li class="mt-1">
                {{ animal.name }} ({{ animal.type }}, {{ animal.weight }} kg)     <button type="button" class="btn btn-sm" (click)="deleteThis(animal.id)"> Delete</button>
              </li>
            }
          </ul>
        </section>
      }
    </section>
  `,
  styleUrls: ['./projects.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule],
})

export class ProjectsComponent {
  private readonly analytics = inject(AnalyticLogger);
  private readonly animalsService = inject(Animals);
  #router = inject(Router);
  createAnimal = this.animalsService.createAnimal();
  deleteAnimal = this.animalsService.deleteAnimal();

  form = new FormGroup({
      name: new FormControl('', Validators.required),
      type: new FormControl('mammal', Validators.required),
      weight: new FormControl(0, [Validators.required, Validators.min(0), Validators.max(10000)]),
  });

  onSubmit() {
    if (!this.form.valid) return;

    const animalRquest: Animal = {
      id: 0, // Assuming a new animal will have an ID of 0 or it will be generated by the backend
      name: this.form.get('name')?.value ?? '',
      type: this.form.get('type')?.value ?? 'mammal',
      weight: this.form.get('weight')?.value ?? 0,
    };
    this.createAnimal.mutate(animalRquest, {
      onSuccess: () => {
        this.animals.refetch();
        this.form.reset();
      },
      onError: (error: Error) => {
        console.error('Failed to create animal', error);
      },
    }); 
  }

  animals = injectQuery(() => ({
    queryKey: ['animals'],
    queryFn: this.animalsService.getAnimalsQueryFn(),
  }));

  protected trackProjectsViewed(): void {
    this.analytics.trackEvent('projects_viewed', 'projects-page');
  }

  protected deleteThis(id: number): void {
    this.deleteAnimal.mutate(id, {
      onSuccess: () => {
        this.animals.refetch();
      },
      onError: (error: Error) => {
        console.error('Failed to delete animal', error);
      },
    });
  }
}
